bundled the testfiles
CPMpy/fuzz-test pull request #1
Opened 2024-07-18 10:22 UTC by MilanPesa

moved the test files to testfiles.
created a fuzz_test.py file to automaticly run all the tests

2024-07-19 13:00 UTC, Wout4 commented
The parallel executions works, and I like the run parameters, nice!
A quick update to the readme would be helpful to run the tests the intended way. 
Also what to do with the output file, but I guess that's next?

maybe we want the option to not run in parallel and just choose one test, but I think running all of them is fine for now.

2024-07-20 07:57 UTC, tias requested changes
Good start, but the processing is a bit different then expected.

Also the user friendlyness of the argparse and the output printing deserves some love (see comments)

When testing, If I run it for 1 or 10 minutes, I always get 'Succ... 0 tests, 0 failed'.

In terms of usability, I would have appreciated output like:

"""
Using solver 'ortools' with models in 'models/' and writing to 'output/'.

Will use X parallel executions, starting...
- running verifier '...' on model '(only the final name)' with X mutations
- running verifier '...' on model '(only the final name)' with X mutations
- running verifier '...' on model '(only the final name)' with X mutations
ERROR found, writing to '...'
- running verifier '...' on model '(only the final name)' with X mutations
- running verifier '...' on model '(only the final name)' with X mutations
"""
perhaps each line preceeded by T1, T2 etc for its thread/process identifier.

also, perhaps we should put a timeout in individual runs? maybe that is what is going wrong now, that an individual run takes more than 10 mins?

2024-07-20 07:57 UTC, tias commented on fuzz_test.py
> +def write_test_data(lock, output_dir: str, test_results: dict, start_time: float, current_amount_of_tests, current_amount_of_error, solver: str, models: list, permutations: int, skip_global_constrain
at this point (early in the file) I don't understand why this would be needed, every thread can write its own file after finishing, there is no problem if an unfinished one gets killed and can't write its result?

2024-07-20 07:57 UTC, tias commented on fuzz_test.py
> +        print("\n executed tests for "+str(math.floor((time.time()-start_time)/60))+" minutes writing the data...")
better separate your concepts a bit better, this should just print 'executed for x minutes'.
the 'writing the data' is a separate concern; also the code below does not do any writing, so you should not print here that it is doing that, this is called 'separation of concerns' and leads to more maintainable code

2024-07-20 07:57 UTC, tias commented on fuzz_test.py
> +    available_solvers = ["ortools","z3"]
why only those? check cpmpy docs on how to get the list of solvers supported on the system, call that

2024-07-20 07:57 UTC, tias commented on fuzz_test.py
> +    parser.add_argument("-H", "--Help", help = "To use fuzz test give: the params --solver", required=False, default = "")
something odd here, if you add this, then doing self.py -H should probably print help, but that is not what is coded here, in the help you write an incomplete help, but that is not shown when doing -H, which expects an argument. Probably just best drop this one? or make it print the usage (in code below, if -h/-H was given)

2024-07-20 07:57 UTC, tias commented on fuzz_test.py
> +    parser.add_argument("-s", "--solver", help = "The Solver to use", required = True,type=str,choices=available_solvers)
you can set a default here... namely the default cpmpy solver, see docs (smth like SolverLookup.get() or whatever code that calls)

2024-07-20 07:57 UTC, tias commented on fuzz_test.py
> +    parser.add_argument("-m", "--models", help = "The path to load the models", required=True, type=str)
you can also set a default here, if you run it from the repo, it is models/ right?

2024-07-20 07:57 UTC, tias commented on fuzz_test.py
> +    parser.add_argument("-o", "--output_dir", help = "The directory to store the output", required=True)
if you also set a default here, then just run `file.py` will work, which is a usability bonus... it can be a temp dir, or it can be 'out/', no opinion at this point

2024-07-20 07:57 UTC, tias commented on fuzz_test.py
> +    parser.add_argument("-a", "--bug_treshold", help = "The bug treshold when to quit", required=False, default=0 ,type=check_positive)
why -a if the long form is --bug_threshold, better '-b' and '--bug-threshold' (note the spelling and the more consistent -)

2024-07-20 07:57 UTC, tias commented on fuzz_test.py
> +    parser.add_argument("-a", "--bug_treshold", help = "The bug treshold when to quit", required=False, default=0 ,type=check_positive)
also the help is too cryptic for me 'bug threshold when to quit'?
is this a maximum nr of bugs to find? is it mutually exclusive to --minutes?
maybe make both --max-bugs and --max-minutes, note that I think it should be possible to set both to 0 (by default) which means it just keeps running indefinitely...

2024-07-20 07:57 UTC, tias commented on fuzz_test.py
> +    parser.add_argument("--permutations", help = "The amount of permutations", required=False, default=5 ,type=check_positive)
where did you get the terminology permutation from? do you mean mutations?
e.g. '-m' '--mutations-per-model' "How many times to apply a mutation before testing"

2024-07-20 07:57 UTC, tias commented on fuzz_test.py
> +    # check if all the model dirs exists
'all'? there is only one?

2024-07-20 07:57 UTC, tias commented on fuzz_test.py
> +    # create the output dir if it does not yet exists
add to the help above (will be created if it does not exist)

2024-07-20 07:57 UTC, tias commented on fuzz_test.py
> +    processes = []
I'm a bit surprised here, do I understand correctly that you create 1 process for every type of mutation?

How does it control how many threads are used? and does it mean it is limited to len(processes)?

I was expected it would launch X processes (e.g. nr of CPU's), and each one would randomly choose one of the verifiers, launch it (which would sample 1 model, mutate it, test it and return) and repeat chosing a verifier, launching it...

2024-07-20 07:57 UTC, tias commented on fuzz_test.py
> +            print("\n Succesfully executed " +str(current_amount_of_tests.value) + " tests, "+str(current_amount_of_error.value)+" tests failed")
If I run it for 1 or 10 minutes, I always get 'Succ... 0 tests, 0 failed'.

In terms of usability, I would have appreciated output like:

"""
Using solver 'ortools' with models in 'models/' and writing to 'output/'.

Will use X parallel executions, starting...
- running verifier '...' on model '(only the final name)' with X mutations
- running verifier '...' on model '(only the final name)' with X mutations
- running verifier '...' on model '(only the final name)' with X mutations
ERROR found, writing to '...'
- running verifier '...' on model '(only the final name)' with X mutations
- running verifier '...' on model '(only the final name)' with X mutations
"""

2024-07-22 11:34 UTC, MilanPesa commented on fuzz_test.py
> +    processes = []
Now i create a process for eacht type of test (equivalance_test, metamorphic_test, model_counting_test, optimization_test, solution_test) and then 1 process that writes data every second and 1 process that checks if the timout has been reached so it are always 7 processes. But indeed we could create an X amount of processes that will continously run 1 random test (equivalance, metamorphic ,...) and repeats it

2024-07-22 11:39 UTC, MilanPesa commented on fuzz_test.py
> +def write_test_data(lock, output_dir: str, test_results: dict, start_time: float, current_amount_of_tests, current_amount_of_error, solver: str, models: list, permutations: int, skip_global_constrain
Now i write the results of all the test in 2 files (a txt and pickle file), these files containt the information about all the tests.
in the way i do it now i would need to write 5 difrent files (since i split up the processes by tests types).

But as you also suggested by setting the amount of processes with a parameter and then randomly run 1 test then i can indeed make the processes itself write to the 2 files and would not need a seperate writing process

2024-07-22 11:42 UTC, MilanPesa commented on fuzz_test.py
> +    parser.add_argument("-m", "--models", help = "The path to load the models", required=True, type=str)
how i wrote it it wasn't you needed to give all the dirs of models seperatly seppareted by a "," thats why you got the 0 tests executed 0 failed. now i addedi t so that you can give indeed the models dir as a parameter, this is indeed more user friendly and logical

2024-07-22 12:30 UTC, tias commented
re: some reply on some comment above.

Do I understand that you log all calls into files then?

I think you can just 'print' the ones that succeed on screen, and only log those that fail... we don't intend to revisit use a succeeding test ever...

2024-07-22 12:39 UTC, MilanPesa commented
No now i log the amount of tests executed and the amount of passed/failed tests.
And then for each failed tests i log the reason why, the mutated model,... here is a quick example of the output right now:
```

Fuzz Test output: 
Test Parameters: 
		Tested the models: models
		Used solver: ortools 
		Random seed: 0
		Fuzz test parameters: mutations_per_model=5, skip_global_constraints=False

Executed 84 tests in 0 minutes,  80 tests passed 4 tests failed

solution_tests:
	amount of executed tests: 29, passed tests 28 failed test 1

metamorphic_tests:
	amount of executed tests: 29, passed tests 29 failed test 0

optimization_tests:
	amount of executed tests: 4, passed tests 3 failed test 1

model_counting_tests:
	amount of executed tests: 16, passed tests 15 failed test 1

equivalance_tests:
	amount of executed tests: 6, passed tests 5 failed test 1

Failed Tests:

	solution_tests:
		failed test 1:
			type: failed_model
			model:
			        (The model)
		        originalmodel: 
				models\pickle-test_constraints\sat\Pickled16878061558174472
			mutators: 
                                (the used mutators)
          ... and so on for all the 5 tests
```

2024-07-23 15:28 UTC, tias reviewed
good, almost there

2024-07-23 15:28 UTC, tias commented on fuzz_test.py
> +def time_out_process(mins : int, current_amount_of_error, max_failed_tests: int, start_time: float) -> None:
do you really need this? would be cleaner without?
e.g. current_amount_of_error.value < max_failed_tests can be tested within the loops...
also time.time() < end_time can be tested within the loops: you run the solver with a time_limit that can not exceed end_time; and that's it? that it goes a bit overtime is not an issue....

2024-07-23 15:28 UTC, tias commented on fuzz_test.py
> +    available_solvers = list(map(getsolvernames, SolverLookup.base_solvers()))
the inline def of a function with a one line return and this use with list/map is too indirect; try being more compact, like:
available_solvers = [solver[0] for solver in SolverLookup.base_solvers()]

However, we have a better function, that checks for the solvers available on the system... `cp.SolverLookup.solvernames()`

2024-07-23 15:28 UTC, tias commented on fuzz_test.py
> +    parser.add_argument("--max-failed-tests", help = "The maximum amount of test that may fail before quitting the application (by default an infinite amount of tests can fail). if the maximum amount
uit/quit

2024-07-23 15:28 UTC, tias commented on fuzz_test.py
> +    test_results = manager.dict()
I don't think you still use this

2024-07-23 15:28 UTC, tias commented on verifiers/verifier_runner.py
> +    if Path('cpmpy-bigtest-private').exists():
thats not supposed to be here I think

2024-07-23 15:28 UTC, tias commented on verifiers/verifier_runner.py
> +            random_verifier = verifiers[random.randint(0,len(verifiers)-1)]
`random.choice()` or something named similarly exists for this

2024-07-23 15:28 UTC, tias commented on verifiers/verifier_runner.py
> +            fmodel = fmodels[0]
also here r.choice

2024-07-23 15:28 UTC, tias commented on verifiers/verifier_runner.py
> +            if not (error == None) and current_amount_of_error.value < max_error_treshold:
why that second check? if there are that many pretend you didn't find this one?

2024-07-23 15:28 UTC, tias commented on verifiers/verifier_runner.py
> +            if not (error == None) and current_amount_of_error.value < max_error_treshold:
just write it is what I mean...

2024-07-23 15:31 UTC, tias commented
als ik keyboard interrupt krijg ik steeds

"""
Succesfully executed 611 tests, 28 tests failed
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tias/research/cpmpy/fuzz-test/fuzz_test.py", line 30, in time_out_process
    time.sleep(1)
KeyboardInterrupt
"""

2024-07-23 15:34 UTC, MilanPesa commented on fuzz_test.py
> +def time_out_process(mins : int, current_amount_of_error, max_failed_tests: int, start_time: float) -> None:
The reason i do it there is that now when you quit the application with a keyboard intterupt it will quit within 1-3 seconds
if i do this check in the verifiers it could take a lot longer to quit

if the verifier is running a test it can take up to 200 seconds to finish and after it the test is finished it will again check if the timout has been reached and so taking a loner time to quit the application

2024-07-23 15:42 UTC, MilanPesa commented on fuzz_test.py
> +def time_out_process(mins : int, current_amount_of_error, max_failed_tests: int, start_time: float) -> None:
But i can move the check to the verifiers if it is not that important to quit exactly after X minutes

2024-07-24 09:24 UTC, tias approved these changes
looks good, up to the timeout point needing a decision

also runs smoothly on my machine

2024-07-24 09:26 UTC, tias commented
OK, my comment did not come through in the review...

every verify call calls a solver, and that solver can be given a time_limit. So, every thread can ensure that the global time limit is respected. This would be imho a cleaner option (one less thread being run) and more maintianble (the logic is in the individual thread-running code).
What does @Wout4 think?

2024-07-24 15:24 UTC, Wout4 commented
Exact timeout is not so important I would say, can simply be the solver timeout. But most of the verifiers also call the solver before mutations (to get the initial optimal value or solution count) so actual time could be as high as twice the timeout then? Or we neglect this initial call assuming we only have small inputs.

2024-07-24 20:42 UTC, tias reviewed
refactoring the timeout checks hints

2024-07-24 20:42 UTC, tias commented on fuzz_test.py
> +def time_out_process(mins : int, current_amount_of_error, max_failed_tests: int, start_time: float) -> None:
based on the discussion, yes drop it here and check it in the subthreads (+ give the solver a timeout, I will leave some notes)

2024-07-24 20:42 UTC, tias commented on fuzz_test.py
> +    process_args = (current_amount_of_tests, current_amount_of_error, lock, args.solver, args.mutations_per_model ,models ,max_failed_tests,args.output_dir)
you can add the timestamp at which all threads should stop (e.g. time.time() + timedelta(timeout 'in minutes'))

2024-07-24 20:42 UTC, tias commented on verifiers/equivalance_verifier.py
> +                cp.Model(cons).solveAll(solver=solver,time_limit=250, display=lambda: original_sols.add(tuple([v.value() for v in original_vars])))
time_limit should be max(250, max_timestamp'in seconds' - time.time()) e.g. don't exceed the max timestamp...
You can do the same in the `solve(time_limit=)` calls of the other verifiers

2024-07-24 20:42 UTC, tias commented on verifiers/equivalance_verifier.py
> +                    model.solveAll(solver=solver, time_limit=200, display=lambda: new_sols.add(tuple([v.value() for v in original_vars])))
also here

2024-07-24 20:42 UTC, tias commented on verifiers/equivalance_verifier.py
> +                    if model.status().runtime > 190:
this should be the computed time_limit - 10, instead of 200-10 fixed...

2024-07-24 20:42 UTC, tias commented on verifiers/metamorphic_verifier.py
> +                assert (cp.Model(cons).solve()), f"{model_file} is not sat"
here

2024-07-24 20:42 UTC, tias commented on verifiers/metamorphic_verifier.py
> +                    sat = model.solve(solver=solver, time_limit=200)
here, and runtime check below

2024-07-24 20:42 UTC, tias commented on verifiers/verifier_runner.py
> +        while current_amount_of_error.value < max_error_treshold:
and the timestamp check here...

2024-07-25 09:24 UTC, merged