Model checker
CPMpy/fuzz-test pull request #2
Opened 2024-07-25 12:43 UTC by MilanPesa

2024-07-31 07:19 UTC, IgnaceBleukx requested changes
Very useful tool, left some comments (some minor, some more major).
How are the models extracted? Do we need a tool for that as well?

2024-07-31 07:19 UTC, IgnaceBleukx commented on model_checker.py
> +        error_text= """
Write this with "\n" explicitely, this hurts my brain ;)

2024-07-31 07:19 UTC, IgnaceBleukx commented on model_checker.py
> +        a function that will solve a single model and check if an Exception occurs, if so then write the exception details to a file
Alt:
```
A wrapper function for solving a CPMPy model given in a `.pickle` file using a specified solver.
The function catches any runtime-error and writes the error to a file  in `output_dir`.
```

2024-07-31 07:19 UTC, IgnaceBleukx commented on model_checker.py
> +from cpmpy import *
Use `import cpmpy as cp` instead

2024-07-31 07:19 UTC, IgnaceBleukx commented on model_checker.py
> +from os.path import join
Merge the `os` imports please

2024-07-31 07:19 UTC, IgnaceBleukx commented on model_checker.py
> +                assert (len(cons)>0), f"{model_file} has no constraints after l2conj"
What is after `l2conj`? You can just put a signle assert after the `toplevel_list` with the message "The model does not contain any consrtaints" afterwards

2024-07-31 07:19 UTC, IgnaceBleukx commented on model_checker.py
> +                fpcl.close()
When using the `with` control block you don't need to close files explicitely

2024-07-31 07:19 UTC, IgnaceBleukx commented on model_checker.py
> +    parser = argparse.ArgumentParser(description = "A python application to simply check if all your models can be solved without errors")
Alt:
```
A Python script for running a batch of CPMpy models on a specified solver and logging any runtime-errors
```

2024-07-31 07:19 UTC, IgnaceBleukx commented on model_checker.py
> +    parser.add_argument("-s", "--solver", help = "The Solver to use", required = False,type=str,choices=available_solvers, default=available_solvers[0])
Hmm, I would rather have `ortools` to be the default (it ships with CPMpy so will always be installed)
(Also solver, not Solver ;) )

2024-07-31 07:19 UTC, IgnaceBleukx commented on model_checker.py
> +    parser.add_argument("-m", "--models", help = "The path to load the models", required=False, type=str, default="models")
Alt:
```
Directory containing pickled CPMpy model
```

2024-07-31 07:19 UTC, IgnaceBleukx commented on model_checker.py
> +    pool = Pool(cpu_count()-1)
I would make the number of threads to use a parameter to the script; as a user, I just want to run all of the tests in the background and not have my CPU pinned at 100% while doing so

2024-07-31 07:19 UTC, IgnaceBleukx commented on model_checker.py
> +    pool = Pool(cpu_count()-1)
Also, some solvers (like OR-Tools) use multiple cores at once... It may be useful to limit the number of cores used by a solver to 1. (Will need to be done on a solver by solver basis tho...)

2024-07-31 07:19 UTC, IgnaceBleukx commented on model_checker.py
> +    for folder in folders:
Wait, what is the filestructure of the input models? I thought it was just a dir with a bunch of `.pickle` files?

2024-07-31 07:19 UTC, IgnaceBleukx commented on model_checker.py
> +        pool.join()
You use `starmap`, which is synchronous and will wait until all subprocesses are finished, so I don't think you need the `join` here?
Do you want to have the keyboardinterrupt quit the process cleanly?
Here is a nice example on how to do:
https://stackoverflow.com/questions/72967793/keyboardinterrupt-with-python-multiprocessing-pool

2024-07-31 07:19 UTC, IgnaceBleukx commented on model_checker.py
> +    parser.add_argument("-o", "--output-dir", help = "The directory to store the output (will be created if it does not exist).", required=False, type=str, default="output")
The output dir is not actually created anywhere

2024-07-31 11:47 UTC, MilanPesa commented on model_checker.py
> +    parser.add_argument("-s", "--solver", help = "The Solver to use", required = False,type=str,choices=available_solvers, default=available_solvers[0])
The available_solvers[0] is the default solver of cpmpy (and that is indeed ortools)

2024-07-31 12:44 UTC, MilanPesa commented on model_checker.py
> +    for folder in folders:
it was the structure like on git, but now it will read all the pickle file of a dir and all its subdirs

2024-07-31 13:10 UTC, MilanPesa commented on model_checker.py
> +        pool.join()
for some reason the keyboardinterrupt doesnt get caught by python in any way (not in the main process and not in the subprocesses) i tried multiple things including the example you give but it does not wrok

2024-08-01 15:37 UTC, IgnaceBleukx requested changes
Some more comments, the importing is a major problem!; rest of them are minor

2024-08-01 15:37 UTC, IgnaceBleukx commented on model_checker.py
> +                model = pickle.loads(fpcl.read())
There seems a tab too many here.

2024-08-01 15:37 UTC, IgnaceBleukx commented on model_checker.py
> +                cons = toplevel_list(cons)
I'm not sure how this is not crashing, (i'm guessing some pickle-magic imports), but you need to import this function somewhere...

2024-08-01 15:37 UTC, IgnaceBleukx commented on model_checker.py
> +                Model(cons).solve(solver=solver,time_limit=100)
This should be `cp.Model`

2024-08-01 15:37 UTC, IgnaceBleukx commented on model_checker.py
> +                Model(cons).solve(solver=solver,time_limit=100)
Also, you probably want the timeout to be a parameter to the script, 100s seems like a good default but a user (me) might want to change it

2024-08-01 15:37 UTC, IgnaceBleukx commented on model_checker.py
> +        error_text= "\nsolved model file: {model_file}\n\nmodel: {model}\n\nWith solver: {solver}\n\nexception: {exception}\n\nstacktrace: {stacktrace}".format(model_file=model_file, model=model,solv
Can you use f-strings instead?

E.g., 
```python
error_text  = f"{\n solved model file: {model_file}\n\n{model}\n\nWith solver: {solver}\n\nexception:{e}\n\nstacktrace:{traceback.format_exc()}"
```

2024-08-02 11:55 UTC, MilanPesa commented on model_checker.py
> +                cons = toplevel_list(cons)
Is this about the toplevel_list? if so then its fixed.

2024-08-06 07:51 UTC, IgnaceBleukx commented
looks good, just one more re-ordering of the import and good to merge after

2024-08-22 15:53 UTC, tias commented on model_checker.py
> +            assert (len(cons)>0), f"{model_file} has no constraints"
we have models in 'models/pickle_test_globals/optimization_no_cons/' that have no constraints... I think this should not be checked here?

Though for some reason we don't run the model with the objective, which is unintended? e.g. we should just do `model = pickle.loads(); model.solve(solver=solver, time_limit=time_limit)`?

2024-09-02 21:58 UTC, merged