Bug checker
CPMpy/fuzz-test pull request #3
Opened 2024-07-31 14:03 UTC by MilanPesa

2024-08-02 09:49 UTC, IgnaceBleukx requested changes
Nice refactoring, but quite some beaty-errors and readibility improvements necessry

I did not get through all files in detail, but many of the comments also apply to the files I left no comments to

2024-08-02 09:49 UTC, IgnaceBleukx commented on bug_checker.py
> +    result = pool.starmap(run_cmd, zip(files,repeat(args.cmd),repeat(args.output_dir)))
Same comment as on the model_checker branch; you should use the `with` construct and not explicitely close the pool etc

2024-08-02 09:49 UTC, IgnaceBleukx commented on bug_checker.py
> +from verifiers.solution_verifier import Solution_Verifier
Add a newline before this one.
Also, it probably makes sense to make a `__init__` file in verifiers and put all imports there.

2024-08-02 09:49 UTC, IgnaceBleukx commented on bug_checker.py
> +            verifiers = {"solution verifier" : Solution_Verifier(*verifier_args),"optimization verifier": Optimization_Verifier(*verifier_args), "model count verifier": Model_Count_Verifier(*verifier
It would be better to make a helper function "lookup_verifier" or smt like that containing this logic.
The helper function would then return the class of the verifier and you can init it here with the args

2024-08-02 09:49 UTC, IgnaceBleukx commented on bug_checker.py
> +            verifier_args = [error_data["solver"], error_data["mutations_per_model"], {}, time.time()*3600, error_data["seed"]]
For readibility and clarity: use kwargs instead of args (i.e., this list should become a dictionary instead).

2024-08-02 09:49 UTC, IgnaceBleukx commented on bug_checker.py
> +        function to rerun a previously failed model to see if the error is still present or not
Make clear it is a fuzz-tested model! I was trying to rerun a failed model outputted by the `model_checker` which of course does not work

2024-08-02 09:49 UTC, IgnaceBleukx commented on bug_checker.py
> +            new_error_Data = error_data
Euh, dictionaries are mutable... So you either need to explicitely copy it here as this statement will have no effect.
That being said, I don't think you actually need to copy it, you can just modify the object and write it to file

2024-08-02 09:49 UTC, IgnaceBleukx commented on bug_checker.py
> +            if error != None:
use `if error is not None`

2024-08-02 09:49 UTC, IgnaceBleukx commented on bug_checker.py
> +        original_cons = sorted(error_data["error"]["constraints"], key=lambda c: -len(get_variables(c)))
Don't sort here, keep the set of constraints as in the original model

2024-08-02 09:49 UTC, IgnaceBleukx commented on bug_checker.py
> +            verifiers = {"solution verifier" : Solution_Verifier(*verifier_args),"optimization verifier": Optimization_Verifier(*verifier_args), "model count verifier": Model_Count_Verifier(*verifier
Same as above, use helper function and kwargs

2024-08-02 09:49 UTC, IgnaceBleukx commented on bug_checker.py
> +            for con in original_cons:
Do we want to "toplevel_list" this set of constraints? I'm guessing yes!

2024-08-02 09:49 UTC, IgnaceBleukx commented on bug_checker.py
> +    args = parser.parse_args()
Here I would also like to be able to set the number of cores to use in multiprocessing

2024-08-02 09:49 UTC, IgnaceBleukx commented on bug_checker.py
> +        mimnimize_bug(failed_model_file,output_dir)
Defensive programming: add a `else` block with clear error of an unknown cmd

2024-08-02 09:49 UTC, IgnaceBleukx commented on bug_checker.py
> +                if new_error != None:
use `is not None`

2024-08-02 09:49 UTC, IgnaceBleukx commented on bug_checker.py
> +        error_data = pickle.loads(fpcl.read())
Some comment on how `error_data` is structured might be useful

2024-08-02 09:49 UTC, IgnaceBleukx commented on bug_checker.py
> +    if not Path(args.output_dir).exists():
Does this also work if a sub-dir does not exist? E.g., if I put as output argument "dir/that/does/not/exist" will it create it?

2024-08-02 09:49 UTC, IgnaceBleukx commented on fuzz_test_utils/output_writer.py
> +    execution_time_text = str(int(error_data["execution_time"])) #str(math.floor(error_data["execution_time"]/60)) #+ " minutes " + str(math.floor(error_data["execution_time"]%60)) + " seconds"
stray comment

2024-08-02 09:49 UTC, IgnaceBleukx commented on fuzz_test_utils/output_writer.py
> +    if error_data["error"]["type"] != "fuzz_test_crash":
(future) maybe we should make an enumerable for the types of crashes, instead of using strings

2024-08-02 09:49 UTC, IgnaceBleukx commented on fuzz_test_utils/output_writer.py
> +        error_text+= '''\
This also hurts my brain ; )

2024-08-02 09:49 UTC, IgnaceBleukx commented on verifiers/equivalance_verifier.py
> +from fuzz_test_utils.mutators import *
You can use `from ..fuz_test_utils.mutators import *`

also, re-order these imports a bit (global advice):
1. python-native imports
2. cpmpy-imports
3. imports from the same package

2024-08-02 09:49 UTC, IgnaceBleukx commented on verifiers/equivalance_verifier.py
>  class Equivalance_Verifier(Verifier):
Add a docstring for what this verifier actually does

2024-08-02 09:49 UTC, IgnaceBleukx commented on verifiers/equivalance_verifier.py
> +    def __init__(self,solver: str, mutations_per_model: int, exclude_dict: dict, max_duration: float, seed: int):
"max_duration" should renamed to "time_limit"

2024-08-02 09:49 UTC, IgnaceBleukx commented on verifiers/verifier.py
> +        self.mutators = None
Why not initialize these variables with the list of all mutators?

2024-08-02 09:49 UTC, IgnaceBleukx commented on verifiers/equivalance_verifier.py
> +    def solve_model(self) -> dict:
I'm guessing this function name is from older code; better to rename it to "verify"

2024-08-02 09:49 UTC, IgnaceBleukx commented on verifiers/equivalance_verifier.py
> +            cp.Model(self.cons).solveAll(solver=self.solver,time_limit=max(1,min(250,self.max_duration-time.time())), display=lambda: self.original_sols.add(tuple([v.value() for v in self.original_va
Please put each argument on a newline, this is very unreadable, even if you know what it's supposed to do

2024-08-02 09:49 UTC, IgnaceBleukx commented on verifiers/equivalance_verifier.py
> +            change = new_sols ^ self.original_sols
Nice! But for readibility the actual method might be better... (I think it's called `symmetric_difference` or smt like that

2024-08-02 09:49 UTC, IgnaceBleukx commented on verifiers/equivalance_verifier.py
> +            if isinstance(e,(CPMpyException, NotImplementedError)):
tab too many

2024-08-02 09:49 UTC, IgnaceBleukx commented on verifiers/equivalance_verifier.py
> +        return {"type": "failed_model","model": model, "originalmodel": self.model_file, "mutators": self.mutators, "constraints":self.cons }
use the dict-initializer (same for the other return statements)
```python
return dict(type="failed_model",
            model=model,
            original_model=self.model_file,
            ....
)
```

2024-08-02 09:49 UTC, IgnaceBleukx commented on verifiers/verifier.py
> +    def solve_model(self) -> dict:
So this one should be renamed to "verify"

2024-08-02 09:49 UTC, IgnaceBleukx commented on verifiers/verifier.py
> +        pass
Throwing an error is safer (e.g., `raise ValueError(f"method 'solve_model' is not implemented for class {type(self)}")`)

2024-08-02 09:49 UTC, IgnaceBleukx commented on verifiers/verifier.py
> +
lots of whitespace

2024-08-02 09:49 UTC, IgnaceBleukx commented on verifiers/verifier_runner.py
> +    random_seed = random.randint(0, 2**32 - 1) # the 2**32 - 1 is the max int
This does not make sense... Either you initialize the seed with a given integer (which would be good), or you don't initialize it at all... Initializing with an random int is a null-operation

2024-08-02 09:49 UTC, IgnaceBleukx commented on verifiers/verifier_runner.py
> +    random_seed = random.randint(0, 2**32 - 1) # the 2**32 - 1 is the max int
So I would make random_seed an argument (default None) to the function and then you can just put `random.seed(seed)` and `np.random.seed(seed)`. Then you also don't need the random_state object

2024-08-02 16:48 UTC, MilanPesa commented on verifiers/verifier_runner.py
> +    random_seed = random.randint(0, 2**32 - 1) # the 2**32 - 1 is the max int
so i first generate a random number, then i use the number for the RandomState and to save it to the files.

If dont use the RandomState each processes will inhert the seed from the parent process and create the exact same tests (which we dont want)

also the np.random.seed isnt thread safe it seems so its better not to use it?

2024-08-06 08:10 UTC, IgnaceBleukx requested changes
Great improvement! Some minor comments still but looks good overall

2024-08-06 08:10 UTC, IgnaceBleukx commented on bug_checker.py
> +            verifier_kwargs = {'solver': error_data["solver"], "mutations_per_model": error_data["mutations_per_model"], "exclude_dict": {}, "time_limit": time.time()*3600, "seed": error_data["seed"]
For intializing these, it's more readible if you use `dict(key1=val1, key2=val2)` etc, ideally, each key on a newline

2024-08-06 08:10 UTC, IgnaceBleukx commented on bug_checker.py
> +            verifier_kwargs = {'solver': error_data["solver"], "mutations_per_model": error_data["mutations_per_model"], "exclude_dict": {}, "time_limit": time.time()*3600, "seed": error_data["seed"]
Or actually, now that you get the verifier lookup, you could just put the args there (line 100).

```python
vrf_cls = lookup_verifier(error_data['verifier'])
verifier = vrf_cls(solver=error_data['solver'],
                   mutations_per_model=...,
)
new_error = verifier.rerun(new_error_dict)


```

2024-08-06 08:10 UTC, IgnaceBleukx commented on fuzz_test_utils/output_writer.py
> +    execution_time_text = str(math.floor(error_data["execution_time"]/60)) + " minutes " + str(math.floor(error_data["execution_time"]%60)) + " seconds"
Can be somewhat cleaner using either f-strings

2024-08-06 08:10 UTC, IgnaceBleukx commented on verifiers/__init__.py
> +    else:
Error would be more appropriate here

2024-08-06 08:10 UTC, IgnaceBleukx commented on verifiers/equivalance_verifier.py
> +            return dict(type=Fuzz_Test_ErrorTypes.internalcrash,model=model, originalmodel=self.model_file, mutators=self.mutators,constraints=self.cons ,exception=e,stacktrace=traceback.format_exc()
Use new-lines for each keyword, my code editor is not that wide ;)

2024-08-06 08:10 UTC, IgnaceBleukx commented on verifiers/verifier_runner.py
> +    random_seed = random.randint(0, 2**32 - 1) # the 2**32 - 1 is the max int
Hmm, I'm not following entirely I think, is this runner also shared with the actual fuzz-tester then? Or is it only used for the rerunning of bugged models?

2024-08-06 09:52 UTC, MilanPesa commented on verifiers/verifier_runner.py
> +    random_seed = random.randint(0, 2**32 - 1) # the 2**32 - 1 is the max int
This woul only be used to rerun/minimize bugged models

2024-08-06 10:20 UTC, MilanPesa commented on verifiers/verifier_runner.py
> +    random_seed = random.randint(0, 2**32 - 1) # the 2**32 - 1 is the max int
nvm it seem to work now with the standard random.seed (before it gave strange behevior, i probably did something wrong  before then)

2024-09-16 15:13 UTC, closed without merging