Create fuzz_test_rerunner.py
CPMpy/fuzz-test pull request #7
Opened 2024-09-18 12:59 UTC by MilanPesa

added a  fuzz_test_rerunner that will allow to rerun a failed fuzz test

2024-09-19 13:26 UTC, Wout4 commented
Would be nice if it works on folders as well, since the file names are a bit tedious to type

2024-09-19 15:45 UTC, MilanPesa commented
it should now work for a directory as well

2024-09-20 08:14 UTC, tias commented
THat's a questionable design choice, there is now almost-duplicate code between the new top function and the code for running a single file...

How about having a function that does it for a single file.
Then, if the arg is file, you run that function. If the arg is a dir, you run a Pool of those functions on the glob of the dir?

2024-09-20 09:54 UTC, MilanPesa commented
Ok i updated the function to run it for a single file.

2024-09-20 10:44 UTC, Wout4 requested changes

2024-09-20 10:44 UTC, Wout4 commented on fuzz_test_rerunner.py
> +    os.makedirs(args.output_dir, exist_ok=True)
it may be a windows thing, but this does not append output_dir to the working directory, you need to give it the full file path

2024-09-20 10:44 UTC, Wout4 commented on fuzz_test_rerunner.py
> +    if os.path.isdir(args.failed_model_file):
same here these do not seem to work as relative paths on windows

2024-09-20 10:44 UTC, Wout4 commented on fuzz_test_rerunner.py
> +    elif os.path.isfile(args.failed_model_file):
same here these do not seem to work as relative paths on windows

2024-09-20 12:31 UTC, MilanPesa commented on fuzz_test_rerunner.py
> +    os.makedirs(args.output_dir, exist_ok=True)
It should be fixed now

2024-09-20 13:44 UTC, Wout4 commented on fuzz_test_rerunner.py
> +                print(Fore.RED+f"{results.count(True)} models failed "+Fore.GREEN +f"{len(results)-results.count(True)} models passed"+Style.RESET_ALL,flush=True )
they failed to fail? I think this should be the opposite or worded differently, maybe something like x models still fail, y models no longer fail.

2024-09-20 13:54 UTC, Wout4 commented on fuzz_test_rerunner.py
> +    os.makedirs(args.output_dir, exist_ok=True)
yes, thanks!

2024-09-20 13:58 UTC, Wout4 commented
So if I understand correctly, the rerunner works by calling the verifiers 'check_model', which skips all the transformation steps, and goes directly to the verification step of comparing the mutated (bugged) model with the original model.
This makes sense for error's during solve, or solutions dissappearing, but not for internal function errors because they may occur during a mutation (for example flatten crashes with a certain input when using flattening as a mutation)

2024-09-20 13:58 UTC, Wout4 commented
so for internal function crashes we need something else, maybe just calling the function with the input that crashed, no need for the whole verifier thing, because we never got to that point

2024-09-20 14:06 UTC, Wout4 commented
Actually even for other bugs types they might be introduced by a buggy transformation, so skipping the transformations will make it seem that the bug is not fixed even if it was fixed..

2024-09-20 14:32 UTC, MilanPesa commented
ok i now i dont skip the transformations

2024-10-07 14:16 UTC, Wout4 commented on verifiers/verifier.py
>              return None
this is inside the for loop, only 1 constraint gets generated?

2024-10-07 14:17 UTC, Wout4 commented on verifiers/verifier.py
> +            if gen_mutations_error == None:
this does not generate the same mutations as in the error file, set random seed, or just look in the mutators list?

2024-10-08 09:25 UTC, Wout4 commented
I'm thinking maybe an option to print which errors still fail or not would be nice to get an overview. Other than that seems to work correctly now

2024-10-08 09:44 UTC, merged